# GitHub Copilot setup for illdata project
# This file ensures bun and just are available in the Copilot coding agent environment

steps:
  # Install bun (JavaScript runtime and package manager)
  - name: Install bun
    run: |
      curl -fsSL https://bun.sh/install | bash
      export PATH="$HOME/.bun/bin:$PATH"
      # Verify installation
      "$HOME/.bun/bin/bun" --version
    
  # Install just (command runner)
  - name: Install just
    run: |
      mkdir -p ~/bin
      curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/bin
      export PATH="$HOME/bin:$PATH"
      # Verify installation
      "$HOME/bin/just" --version