import { describe, test, expect, beforeEach } from 'bun:test';

// Mock localStorage for testing
const mockLocalStorage = (() => {
    let store: Record<string, string> = {};
    return {
        getItem: (key: string) => store[key] || null,
        setItem: (key: string, value: string) => { store[key] = value; },
        removeItem: (key: string) => { delete store[key]; },
        clear: () => { store = {}; }
    };
})();

// Mock the global localStorage
Object.defineProperty(global, 'localStorage', {
    value: mockLocalStorage,
    writable: true
});

import { translateSeriesName, normalizeSeriesName, setLanguage, getLanguage } from './locales';

describe('Series Name Translation Tests', () => {
    beforeEach(() => {
        mockLocalStorage.clear();
        setLanguage('en');
    });

    describe('translateSeriesName', () => {
        test('translates base series name to Czech', () => {
            setLanguage('cs');
            expect(translateSeriesName('PCR Positivity')).toBe('PCR pozitivita');
        });

        test('translates averaged series name to Czech', () => {
            setLanguage('cs');
            expect(translateSeriesName('PCR Positivity (28d avg)')).toBe('PCR pozitivita (28d prům.)');
        });

        test('translates custom day shifted series to Czech', () => {
            setLanguage('cs');
            // This is the actual format generated by utils.ts: "shifted by Xd"
            const result = translateSeriesName('PCR Positivity shifted by 370d');
            expect(result).toContain('posunuto o');
            expect(result).toContain('370');
        });

        test('translates wave-based shifted series to Czech', () => {
            setLanguage('cs');
            // This is the actual format generated by utils.ts: "shifted by X wave Yd"
            const result = translateSeriesName('PCR Positivity (28d avg) shifted by 1 wave -347d');
            expect(result).toContain('posunuto o');
            expect(result).toContain('vlna');
            expect(result).toContain('-347');
        });

        test('returns English as-is when language is English', () => {
            setLanguage('en');
            expect(translateSeriesName('PCR Positivity')).toBe('PCR Positivity');
            expect(translateSeriesName('PCR Positivity shifted by 370d')).toBe('PCR Positivity shifted by 370d');
        });
    });

    describe('normalizeSeriesName', () => {
        test('returns English series name as-is', () => {
            expect(normalizeSeriesName('PCR Positivity')).toBe('PCR Positivity');
        });

        test('normalizes Czech base series name to English', () => {
            expect(normalizeSeriesName('PCR pozitivita')).toBe('PCR Positivity');
        });

        test('normalizes Czech averaged series name to English', () => {
            expect(normalizeSeriesName('PCR pozitivita (28d prům.)')).toBe('PCR Positivity (28d avg)');
        });

        test('normalizes Czech custom day shifted series to English', () => {
            // This tests the bug: Czech format "posunuto o X dnů" should normalize back to English
            setLanguage('cs');
            const czechName = translateSeriesName('PCR Positivity shifted by 370d');
            setLanguage('en');
            const normalized = normalizeSeriesName(czechName);
            expect(normalized).toBe('PCR Positivity shifted by 370d');
        });

        test('normalizes Czech wave-based shifted series to English', () => {
            // This tests the bug: Czech format should normalize back to English
            setLanguage('cs');
            const czechName = translateSeriesName('PCR Positivity (28d avg) shifted by 1 wave -347d');
            setLanguage('en');
            const normalized = normalizeSeriesName(czechName);
            expect(normalized).toBe('PCR Positivity (28d avg) shifted by 1 wave -347d');
        });

        test('round-trip translation preserves series name', () => {
            const originalNames = [
                'PCR Positivity',
                'PCR Positivity (28d avg)',
                'PCR Positivity shifted by 370d',
                'PCR Positivity (28d avg) shifted by 1 wave -347d',
                'Antigen Positivity shifted by -180d',
            ];

            originalNames.forEach(original => {
                setLanguage('cs');
                const translated = translateSeriesName(original);
                setLanguage('en');
                const normalized = normalizeSeriesName(translated);
                expect(normalized).toBe(original);
            });
        });
    });

    describe('URL State Round-Trip for Shifted Series', () => {
        test('visibility state is preserved after language switch for shifted series', () => {
            // Simulate sharing a URL with Czech language and shifted series enabled
            setLanguage('cs');
            
            // Get the Czech name for a shifted series
            const englishName = 'PCR Positivity (28d avg) shifted by 1 wave -347d';
            const czechName = translateSeriesName(englishName);
            
            // Verify the Czech name contains expected Czech keywords
            expect(czechName).toContain('pozitivita');
            
            // Now normalize back to English (simulating URL decode on English browser)
            setLanguage('en');
            const normalizedName = normalizeSeriesName(czechName);
            
            // The normalized name should match the original English name
            expect(normalizedName).toBe(englishName);
        });
    });
});
